# Permalinks
permalink:           pretty

# Setup
title:               Mining Online Data for Early Identification of Unsafe Food Products
tagline:             ""
description:         "A Data Science for Social Good 2016 fellowship project."
url:                 "https://uwescience.github.io/DSSG2016-UnsafeFoods/"
baseurl:             "/DSSG2016-UnsafeFoods"

# Custom vars
version:             0.0.1
